// <auto-generated>
//   GENERATED FILE — do not edit by hand.
//
//   The Swift half of the version square (sdk-api-contract.md §1.5). At release time this
//   MUST equal, by ORDINAL STRING EQUALITY:
//     - game-sdk/unity/com.gog.sdk/package.json        "version"
//     - Runtime/GogSdkVersion.g.cs                     GogSdkVersion.Value
//     - the .aar's BuildConfig.SDK_VERSION
//     - this file's GogSDKVersion.value
//     - the XCFramework Info.plist CFBundleShortVersionString
//
//   No semver parsing, ever: a parser silently matches "0.2.1" to "0.2.1.0", which is the
//   exact class of bug the handshake exists to catch.
//
//   The placeholder below is deliberately invalid. An unstamped build FAILS CLOSED at
//   configure time rather than shipping a version that merely looks plausible — see
//   GogConfiguration.validate(). scripts/release/stamp-version.mjs (Phase 1) rewrites it.
// </auto-generated>

public enum GogSDKVersion {
    public static let value = "0.0.0-unstamped"

    /// True when the release script has not run. Checked at configure time.
    static var isUnstamped: Bool { value == "0.0.0-unstamped" }
}
